routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('lang/{lang}', 'LangController@setLanguage')->name('lang');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function (){
    Route::get('/', 'HomeController@getIndex')->name('home');
    Route::get('/dashboard', 'HomeController@getIndex')->name('dashboard');

    //users
    Route::get('/profile', 'UserController@getUserProfile')->name('user.profile.index');
    Route::post('/profile', 'UserController@updateUserProfile')->name('user.profile.update');
    Route::post('/change-password', 'UserController@changePassword')->name('user.profile.change-password');

    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/groups', 'GroupController');
    Route::resource('/menus', 'MenuController');
    Route::resource('/contacts', 'ContactController');
    Route::resource('/pages', 'PageController');

    Route::group(['prefix' => 'services'], function (){
        Route::get('/{slug}', 'ServiceController@index')->name('services.index');
        Route::get('/create/{type}', 'ServiceController@create')->name('services.create');
        Route::post('/store', 'ServiceController@store')->name('services.store');
        Route::get('/edit/{id}', 'ServiceController@edit')->name('services.edit');
        Route::post('/update/{id}', 'ServiceController@update')->name('services.update');
        Route::post('/destroy/{id}', 'ServiceController@destroy')->name('services.destroy');
    });

    Route::get('/about', 'AboutController@index')->name('about.index');
    Route::post('/about', 'AboutController@store')->name('about.store');

    Route::get('/activity-logs', 'ActivityController@getIndex')->name('activity.index');
    Route::post('/activity-logs/clear', 'ActivityController@getClear')->name('activity.clear');

    Route::group(['prefix' => 'setting'], function (){
        Route::get('general', 'SettingController@getGeneral')->name('admin.setting');
        Route::post('email/edit', [
            'as' => 'settings.email.edit',
            'uses' => 'SettingController@postEditEmailConfig',
        ]);
        Route::post('email/test', [
            'as' => 'settings.email.test',
            'uses' => 'SettingController@postTestEmailConfig',
        ]);

        Route::post('general/edit', [
            'as' => 'settings.general.edit',
            'uses' => 'SettingController@postEditGeneral',
        ]);
        Route::group(['prefix' => 'cache'], function () {
            Route::get('', [
                'as'         => 'system.cache',
                'uses'       => 'SettingController@getCacheManagement',
            ]);

            Route::post('clear', [
                'as'         => 'system.cache.clear',
                'uses'       => 'SettingController@postClearCache',

            ]);
        });
    });

});

Route::group(['namespace' => 'Frontend'], function (){
    Route::get('/', 'HomeController@getIndex')->name('frontend.home.index');
    Route::post('/contact-us', 'ContactController@sendContact')->name('frontend.contact.send');

    Route::get('/analytics', function(){
        $analyticsData = Analytics::fetchVisitorsAndPageViews(Spatie\Analytics\Period::days(7));
        dd($analyticsData);
    });

    
});

resources/views/admin/page/add.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('layout.add_page')}}</div>
                        <div class="card-body">
                            <form action="{{route('pages.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">  
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="vi-tab" data-toggle="tab" href="#vi" role="tab" aria-controls="vi" aria-selected="false">{{__('layout.vietnamese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="ja-tab" data-toggle="tab" href="#ja" role="tab" aria-controls="ja" aria-selected="true">{{__('layout.japanese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="en-tab" data-toggle="tab" href="#en" role="tab" aria-controls="en" aria-selected="false">{{__('layout.english')}}</a>
                                        </li>
                                    </ul>
                                
                                    <div class="tab-content tabs-trans" id="myTabContent">
                                        <div class="tab-pane fade show active" id="vi" role="tabpanel" aria-labelledby="vi-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('layout.name')}}</label>
                                                <input type="text" name="vi[title]" value="{{ old('vi.title') }}" class="form-control
                                                @error('vi.title') is-invalid @enderror">
                                                @error('vi.title')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                            </div>
                                            <div class="form-group">
                                                <label>{{__('layout.content')}}</label>
                                                <textarea class="form-control" rows="3" name="vi[content]">{{ old('vi.content') }}</textarea>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="ja" role="tabpanel" aria-labelledby="ja-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('layout.title')}}</label>
                                                <input type="text" name="ja[title]" value="{{ old('ja.title') }}" 
                                                    class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label>{{__('layout.content')}}</label>
                                                <textarea class="form-control" rows="3" name="ja[content]">{{ old('ja.content') }}</textarea>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="en" role="tabpanel" aria-labelledby="en-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('layout.title')}}</label>
                                                <input type="text" name="en[title]" value="{{ old('en.title') }}" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label>{{__('layout.content')}}</label>
                                                <textarea class="form-control" rows="3" name="en[content]">{{ old('en.content') }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <select id="type" class="form-control" name="type">
                                        <option value="1">About us</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="avatar">{{__('layout.image')}}</label>
                                    <div>
                                        {{-- <button id="ckfinder-modal" class="btn btn-primary btn-sm">{{__('action.browse_server')}}</button>
                                        <input id="ckfinder-input" name="image" hidden> --}}
        
                                        <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.upload_from_client')}}</label>
                                        <input type="file" onchange="readImage(this)" name="image" id="upload-photo" hidden/>    
                                    </div>
                                    <img id="img-preview" src="" alt="" class="img-thumbnail">
                                    @error('image')<div class="text-danger">{{ $message }}</div>@enderror
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> {{__('action.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
@push('page-scripts')
<script>
    var button = $('#ckfinder-modal');
    button.click(function(e){
        e.preventDefault();
        selectFileWithCKFinder('#ckfinder-input');
    });
    </script>
@endpush

resources/views/admin/page/edit.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('layout.edit_page')}}</div>
                        <div class="card-body">
                            <form action="{{route('pages.update', $page->id)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <div class="form-group">  
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="vi-tab" data-toggle="tab" href="#vi" role="tab" aria-controls="vi" aria-selected="false">{{__('layout.vietnamese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="ja-tab" data-toggle="tab" href="#ja" role="tab" aria-controls="ja" aria-selected="true">{{__('layout.japanese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="en-tab" data-toggle="tab" href="#en" role="tab" aria-controls="en" aria-selected="false">{{__('layout.english')}}</a>
                                        </li>
                                    </ul>
                                
                                    <div class="tab-content tabs-trans" id="myTabContent">
                                        <div class="tab-pane fade show active" id="vi" role="tabpanel" aria-labelledby="vi-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('layout.name')}}</label>
                                                <input type="text" name="vi[title]" value="{{ old('vi.title', $page->{'title:vi'}) }}" class="form-control
                                                @error('ja.title') is-invalid @enderror">
                                                @error('ja.title')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                            </div>
                                            <div class="form-group">
                                                <label>{{__('layout.content')}}</label>
                                                <textarea class="form-control" rows="3" name="vi[content]">{{ old('vi.content', $page->{'content:vi'}) }}</textarea>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="ja" role="tabpanel" aria-labelledby="ja-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('layout.title')}}</label>
                                                <input type="text" name="ja[title]" value="{{ old('ja.title', $page->{'title:ja'}) }}" 
                                                    class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label>{{__('layout.content')}}</label>
                                                <textarea class="form-control" rows="3" name="ja[content]">{{ old('ja.content', $page->{'content:ja'}) }}</textarea>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="en" role="tabpanel" aria-labelledby="en-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('layout.title')}}</label>
                                                <input type="text" name="en[title]" value="{{ old('en.title', $page->{'title:en'}) }}" class="form-control">
                                            </div>
                                            <div class="form-group">
                                                <label>{{__('layout.content')}}</label>
                                                <textarea class="form-control" rows="3" name="en[content]">{{ old('en.content', $page->{'content:en'}) }}</textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="type">Type</label>
                                    <select id="type" class="form-control" name="type">
                                        <option value="1">About us</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="avatar">{{__('layout.image')}}</label>
                                    <div>
                                        {{-- <button id="ckfinder-modal" class="btn btn-primary btn-sm">{{__('action.browse_server')}}</button>
                                        <input id="ckfinder-input" name="image" hidden> --}}
        
                                        <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.upload_from_client')}}</label>
                                        <input type="file" onchange="readImage(this)" name="image" id="upload-photo" hidden/>    
                                    </div>
                                    <img id="img-preview" src="{{ asset("storage/images/pages/$page->image") }}" alt="" class="img-thumbnail">
                                    @error('image')<div class="text-danger">{{ $message }}</div>@enderror
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> {{__('action.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

@push('page-scripts')
<script>
    var button = $('#ckfinder-modal');
    button.click(function(e){
        e.preventDefault();
        selectFileWithCKFinder('#ckfinder-input');
    });
    </script>
@endpush

resources/views/admin/page/index.blade.php
@extends('admin.app')

@section('title', 'SKR | User')
@section('content')
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <span class="lead"><i class="fa fa-list-ul" aria-hidden="true"></i> {{__('layout.page_list')}}</span>
                        <a href="{{ route('pages.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>
                            {{__('action.create')}}
                        </a>
                    </div>
                    <div class="card-body ">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>{{__('layout.title')}}</th>
                                        <th>{{__('layout.image')}}</th>
                                        <th>{{__('layout.type') }}</th>
                                        <th style="width:40%">{{__('layout.content')}}</th>                                       
                                        <th>{{__('layout.action')}}</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmDeleteItem" tabindex="-1" role="dialog" aria-labelledby="modelLabel"
          aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    {{__('action.delete_confirm')}}
                </div>
                <div id="confirmMessage" class="modal-body">
                    {{__('action.delete_sure', ['obj'=>'user'])}}
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnConfirmDelete" class="btn btn-danger btn-ok"
                            onclick="deleteItem($(this).val())">
                        {{__('action.delete')}}
                    </button>
                    <button type="button" id="confirmCancel" class="btn btn-secondary" data-dismiss="modal"
                            data-toggle="modal" data-target="#confirmDeleteUser">
                        {{__('action.cancel')}}
                    </button>
                </div>
            </div>
        </div>
    </div>
  </section>
</div>
@endsection

@push('page-scripts')
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('pages.index') }}",
        columns: [
            { data: 'title', name: 'title' },
            { data: 'image', name: 'image' },
            { data: 'type', name: 'type' },
            { data: 'content', name: 'content' },
        ],
        columnDefs: [{
            "targets": 4, 
            "data": null,
            "render": function (data) {
                edit_url = "{{ url('admin/pages') }}/" + data.id + "/edit";
                delete_event = ' onclick = checkItemExisted(' + data.id + ') ';
                return '<a class="btn btn-primary btn-sm" href=' + edit_url + '><span class="fa fa-edit"></span></a> ' +
                '<button class="btn btn-sm btn-danger" ' + delete_event + 'id="row_' + data.id + '" data-toggle="modal" data-target="#confirmDeleteItem" >' +
                '<span class="fa fa-trash" ></span></button> ';
            }
        }],
    });

    function checkItemExisted(id) {
        $('#btnConfirmDelete').val(id);
    }

    function deleteItem(id) {
        let delete_URL = "{{ url('admin/pages') }}/" + id;
        let request = $.ajax({
            url: delete_URL,
            type: "DELETE"
        }).done(function (data) {
            $("#confirmDeleteItem").modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
            
            if(data.status_code == 500){
                iziToast.success({
                    title: 'Error',
                    message: data.message,
                    position: 'topRight'
                });
            }
            else {
                $(`#row_${data.row_id}`).closest("tr").remove();
                iziToast.success({
                    title: 'Message',
                    message: data.message,
                    position: 'topRight'
                });
            }
        });
    }
</script>
@endpush