modules/gallery/routes/web.php
<?php

use Facade\FlareClient\View;
use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Modules\Gallery\Http\Controllers', 'middleware' => 'web'], function () {
    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
        Route::post('/banners/status/{id}', 'BannerController@updateStatus')->name('admin.banners.status');
        Route::resource('/banners', 'BannerController');
        Route::resource('/galleries', 'GalleryController');
        Route::get('/file-manager', 'FileManagerController@getIndex')->name('file_manager');
    });
});

modules/gallery/resources/views/banner/add.blade.php
@extends('admin.app')

@section('title', 'SKR | Banners')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
        <form action="{{route('banners.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('Gallery::gallery.add_banner')}}</div>
                        <div class="card-body">
                            <div class="form-group">  
                                <ul class="nav nav-tabs" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="vi-tab" data-toggle="tab" href="#vi" role="tab" aria-controls="vi" aria-selected="false">{{__('layout.vietnamese')}}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="ja-tab" data-toggle="tab" href="#ja" role="tab" aria-controls="ja" aria-selected="true">{{__('layout.japanese')}}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="en-tab" data-toggle="tab" href="#en" role="tab" aria-controls="en" aria-selected="false">{{__('layout.english')}}</a>
                                    </li>
                                </ul>
                            
                                <div class="tab-content tabs-trans" id="myTabContent">
                                    <!--Vietnamese-->
                                    <div class="tab-pane fade show active" id="vi" role="tabpanel" aria-labelledby="vi-tab">
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.title')}}</label>
                                            <input type="text" name="vi[title]" value="{{ old('vi.title') }}" 
                                                class="form-control @error('vi.title') is-invalid @enderror">
                                            @error('vi.title')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                        </div>
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.description')}}</label>
                                            <textarea class="form-control" rows="3" name="vi[description]">{{ old('vi.description') }}</textarea>
                                        </div>
                                    </div>
                                    <!--Japanese-->
                                    <div class="tab-pane fade" id="ja" role="tabpanel" aria-labelledby="ja-tab">
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.title')}}</label>
                                            <input type="text" name="ja[title]" value="{{ old('ja.title') }}" 
                                                class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.description')}}</label>
                                            <textarea class="form-control" rows="3" name="ja[description]">{{ old('ja.description') }}</textarea>
                                        </div>
                                    </div>
                                    <!--English-->
                                    <div class="tab-pane fade" id="en" role="tabpanel" aria-labelledby="en-tab">
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.title')}}</label>
                                            <input type="text" name="en[title]" value="{{ old('en.title') }}" 
                                                class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.description')}}}</label>
                                            <textarea class="form-control" rows="3" name="en[description]">{{ old('en.description') }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="slug">{{__('Gallery::gallery.link')}}</label>
                                <input type="text" class="form-control" name="link" value="{{ old('link') }}">
                            </div>
                            <div class="form-group">
                                <label for="type">{{__('Gallery::gallery.type')}}</label>
                                <select id="type" class="form-control" name="type">
                                    <option value="1">Banner</option>
                                    <option value="2">Slider</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="sort_order">{{__('Gallery::gallery.order')}}</label>
                                <input type="number" class="form-control" name="sort_order" min="0" value="{{ old('sort_order', 0) }}">
                            </div>
                            <div class="form-group">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="gridCheck" name="status" value="1">
                                    <label class="form-check-label" for="gridCheck">Active</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-right">
                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            <label for="">{{__('Gallery::gallery.choose_image')}}</label>
                            <div class="form-group">
                                <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.choose_file')}}</label>
                                <input type="file" onchange="readImage(this)" name="image" id="upload-photo" hidden/>

                                <img id="img-preview" src="" alt="" class="img-thumbnail">
                                @error('image')<div class="text-danger">{{ $message }}</div>@enderror
                            </div>
                            <hr>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        </section>
    </div>
@endsection

modules/gallery/resources/views/banner/edit.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
        <form action="{{route('banners.update', $banner->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('Gallery::gallery.edit_banner')}}</div>
                        <div class="card-body">
                            <div class="form-group">  
                                <ul class="nav nav-tabs" id="myTab" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="vi-tab" data-toggle="tab" href="#vi" role="tab" aria-controls="vi" aria-selected="false">{{__('layout.vietnamese')}}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="ja-tab" data-toggle="tab" href="#ja" role="tab" aria-controls="ja" aria-selected="true">{{__('layout.japanese')}}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="en-tab" data-toggle="tab" href="#en" role="tab" aria-controls="en" aria-selected="false">{{__('layout.english')}}</a>
                                    </li>
                                </ul>
                            
                                <div class="tab-content tabs-trans" id="myTabContent">
                                     <!--Vietnamese-->
                                     <div class="tab-pane fade show active" id="vi" role="tabpanel" aria-labelledby="vi-tab">
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.title')}}</label>
                                            <input type="text" name="vi[title]" value="{{ old('vi.title', $banner->{'title:vi'}) }}" 
                                                class="form-control @error('vi.title') is-invalid @enderror">
                                            @error('vi.title')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                        </div>
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.description')}}</label>
                                            <textarea class="form-control" rows="3" name="vi[description]">{{ old('vi.description', $banner->{'description:vi'}) }}</textarea>
                                        </div>
                                    </div>
                                    <!--Japanese-->
                                    <div class="tab-pane fade" id="ja" role="tabpanel" aria-labelledby="ja-tab">
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.title')}}</label>
                                            <input type="text" name="ja[title]" value="{{ old('ja.title', $banner->{'title:ja'}) }}" 
                                                class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.description')}}</label>
                                            <textarea class="form-control" rows="3" name="ja[description]">{{ old('ja.description', $banner->{'description:ja'}) }}</textarea>
                                        </div>
                                    </div>
                                    <!--English-->
                                    <div class="tab-pane fade" id="en" role="tabpanel" aria-labelledby="en-tab">
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.title')}}</label>
                                            <input type="text" name="en[title]" value="{{ old('en.title', $banner->{'title:en'}) }}" 
                                                class="form-control @error('en.title') is-invalid @enderror">
                                        </div>
                                        <div class="form-group">
                                            <label>{{__('Gallery::gallery.description')}}</label>
                                            <textarea class="form-control" rows="3" name="en[description]">{{ old('en.description', $banner->{'description:en'}) }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="slug">{{__('Gallery::gallery.link')}}</label>
                                <input type="text" class="form-control" name="link" value="{{ old('link', $banner->link) }}">
                            </div>
                            <div class="form-group">
                                <label for="type">{{__('Gallery::gallery.type')}}</label>
                                <select id="type" class="form-control" name="type">
                                    <option value="1">Banner</option>
                                    <option value="2">Slider</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="sort_order">{{__('Gallery::gallery.order')}}</label>
                                <input type="number" class="form-control" name="sort_order" min="0" value="{{ old('sort_order', $banner->sort_order) }}">
                            </div>
                            <div class="form-group">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="gridCheck" name="status" value="1" {{$banner->status==1? 'checked': ''}}>
                                    <label class="form-check-label" for="gridCheck">Active</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-right">
                    <div class="card card-primary card-outline">
                        <div class="card-body">
                            <label for="">{{__('Gallery::gallery.choose_image')}}</label>
                            <div class="form-group">
                                <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.choose_file')}}</label>
                                <input type="file" onchange="readImage(this)" name="image" id="upload-photo" hidden/>

                                <img id="img-preview" src="{{ asset("storage/images/banners/$banner->image") }}" alt="" class="img-thumbnail">
                                @error('image')<div class="text-danger">{{ $message }}</div>@enderror
                            </div>
                            <hr>
                            <div class="text-right">
                                <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        </section>
    </div>
@endsection

modules/gallery/resources/views/banner/index.blade.php
@extends('admin.app')

@section('title', 'SKR | User')
@section('content')
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <span class="lead"><i class="fa fa-list-ul" aria-hidden="true"></i> {{__('Gallery::gallery.gallery_list')}}</span>
                        <a href="{{ route('banners.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>
                            {{__('action.create')}}
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>{{__('Gallery::gallery.image')}}</th>
                                        <th>{{__('Gallery::gallery.title')}}</th>
                                        <th>{{__('Gallery::gallery.type')}}</th>
                                        <th>{{__('Gallery::gallery.order')}}</th>
                                        <th>{{__('Gallery::gallery.active')}}</th>
                                        <th>{{__('layout.action')}}</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmDeleteItem" tabindex="-1" role="dialog" aria-labelledby="modelLabel"
          aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    {{__('action.delete_confirm')}}
                </div>
                <div id="confirmMessage" class="modal-body">
                    {{__('action.delete_sure', ['obj'=>'Image'])}}
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnConfirmDelete" class="btn btn-danger btn-ok"
                            onclick="deleteItem($(this).val())">
                        {{__('action.delete')}}
                    </button>
                    <button type="button" id="confirmCancel" class="btn btn-secondary" data-dismiss="modal"
                            data-toggle="modal" data-target="#confirmDeleteUser">
                        {{__('action.cancel')}}
                    </button>
                </div>
            </div>
        </div>
    </div>
  </section>
</div>
@endsection

@push('page-scripts')
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('banners.index') }}",
        columns: [
            { data: 'image', name: 'image'},
            { data: 'title', name: 'title'},
            { data: 'type_name', name: 'type_name'},
            { data: 'sort_order', name: 'sort_order'},
            { data: 'status', name: 'status'},
        ],
        columnDefs: [{
            "targets": 5, 
            "data": null,
            "render": function (data) {
                edit_url = "{{ url('admin/banners') }}/" + data.id + "/edit";
                delete_event = ' onclick = checkItemExisted(' + data.id + ') ';
                return '<a class="btn btn-primary btn-sm" href=' + edit_url + '><span class="fa fa-edit"></span></a> ' +
                '<button class="btn btn-sm btn-danger" ' + delete_event + 'id="row_' + data.id + '" data-toggle="modal" data-target="#confirmDeleteItem" >' +
                '<span class="fa fa-trash" ></span></button> ';
            }
        }],
    });

    function checkItemExisted(id) {
        $('#btnConfirmDelete').val(id);
    }

    function deleteItem(id) {
        let delete_URL = "{{ url('admin/banners') }}/" + id;
        let request = $.ajax({
            url: delete_URL,
            type: "DELETE"
        }).done(function (data) {
            $("#confirmDeleteItem").modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
            if(data.status_code == 500){
                iziToast.success({
                    title: 'Error',
                    message: data.message,
                    position: 'topRight'
                });
            }
            else {
                $(`#row_${data.row_id}`).closest("tr").remove();
                iziToast.success({
                    title: 'Message',
                    message: data.message,
                    position: 'topRight'
                });
            }
        });
    }

    function changeStatus(id){
        ajax_URL = "{{ url('admin/banners/status') }}/" + id;
        let request = $.ajax({
            url: ajax_URL,
            method: "POST"
        }).done(function (data) {
            if(data.status_code == 500){
                iziToast.success({
                    title: 'Error',
                    message: data.message,
                    position: 'topRight'
                });
            }
            else {
                iziToast.success({
                    title: 'Message',
                    message: data.message,
                    position: 'topRight'
                });
            }
        });
    }
</script>
@endpush