modules/post/routes/web.php
<?php

use Facade\FlareClient\View;
use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Modules\Post\Http\Controllers', 'middleware' => 'web'], function () {
    Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

        Route::post('/categories/status/{id}', 'CategoryController@updateStatus')->name('admin.categories.status');
        Route::resource('/categories', 'CategoryController');

        Route::post('/posts/status/{id}', 'PostController@updateStatus')->name('admin.posts.status');
        Route::resource('/posts', 'PostController');
    });
});

modules/post/resources/views/category/add.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('Post::category.add_category')}}</div>
                        <div class="card-body">
                            <form action="{{route('categories.store')}}" method="POST">
                                @csrf
                                <div class="form-group">  
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="vi-tab" data-toggle="tab" href="#vi" role="tab" aria-controls="vi" aria-selected="false">{{__('layout.vietnamese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="ja-tab" data-toggle="tab" href="#ja" role="tab" aria-controls="ja" aria-selected="true">{{__('layout.japanese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="en-tab" data-toggle="tab" href="#en" role="tab" aria-controls="en" aria-selected="false">{{__('layout.english')}}</a>
                                        </li>
                                    </ul>
                                
                                    <div class="tab-content tabs-trans" id="myTabContent">
                                        <div class="tab-pane fade show active" id="vi" role="tabpanel" aria-labelledby="vi-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('Post::category.name')}}</label>
                                                <input type="text" id="name" name="vi[name]" value="{{ old('vi.name') }}" class="form-control
                                                @error('vi.name') is-invalid @enderror">
                                                @error('vi.name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="ja" role="tabpanel" aria-labelledby="ja-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('Post::category.name')}}</label>
                                                <input type="text" id="name" name="ja[name]" value="{{ old('ja.name') }}" 
                                                    class="form-control">
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="en" role="tabpanel" aria-labelledby="en-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('Post::category.name')}}</label>
                                                <input type="text" id="name" name="en[name]" value="{{ old('en.name') }}" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="slug">{{__('Post::category.permalink')}}</label>
                                    <div class="d-flex text-black">
                                        <span class="default-slug"><mark>{{url('/')}}/<mark></span>
                                        <div class="input-slug">
                                            <input type="text" id="slug" name="slug" value="{{ old('slug') }}" class="form-control @error('slug') is-invalid @enderror" 
                                                onfocusout="convertToSlug($(this))">
                                            @error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputState">{{__('Post::category.parent')}}</label>
                                    <select id="inputState" class="form-control" name="parent_id">
                                        <option value="" selected>None</option>
                                        @foreach ($categories as $cate)
                                            <option value="{{$cate->id}}">{{ $cate->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                {{-- <div class="form-group">
                                    <div class="form-check">
                                      <input class="form-check-input" type="checkbox" id="gridCheck" name="status" value="1">
                                      <label class="form-check-label" for="gridCheck">
                                        Active
                                      </label>
                                    </div>
                                </div> --}}
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

modules/post/resources/views/category/edit.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('Post::category.edit_category')}}</div>
                        <div class="card-body">
                            <form action="{{route('categories.update', $category->id)}}" method="POST">
                                @csrf
                                @method('PUT')
                                <div class="form-group">  
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="vi-tab" data-toggle="tab" href="#vi" role="tab" aria-controls="vi" aria-selected="false">{{__('layout.vietnamese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="ja-tab" data-toggle="tab" href="#ja" role="tab" aria-controls="ja" aria-selected="true">{{__('layout.japanese')}}</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="en-tab" data-toggle="tab" href="#en" role="tab" aria-controls="en" aria-selected="false">{{__('layout.english')}}</a>
                                        </li>
                                    </ul>
                                
                                    <div class="tab-content tabs-trans" id="myTabContent">
                                        <div class="tab-pane fade show active" id="vi" role="tabpanel" aria-labelledby="vi-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('Post::category.name')}}</label>
                                                <input type="text" id="name" name="vi[name]" value="{{ old('vi.name', $category->{'name:vi'}) }}" class="form-control
                                                @error('vi.name') is-invalid @enderror">
                                                @error('vi.name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="ja" role="tabpanel" aria-labelledby="ja-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('Post::category.name')}}</label>
                                                <input type="text" id="name" name="ja[name]" value="{{ old('ja.name', $category->{'name:ja'}) }}" 
                                                    class="form-control">
                                            </div>
                                        </div>
                                        <div class="tab-pane fade" id="en" role="tabpanel" aria-labelledby="en-tab">
                                            <div class="form-group">
                                                <label for="name">{{__('Post::category.name')}}</label>
                                                <input type="text" id="name" name="en[name]" value="{{ old('en.name', $category->{'name:en'}) }}" class="form-control">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="slug">{{__('Post::category.permalink')}}</label>
                                    <div class="d-flex text-black">
                                        <span class="default-slug"><mark>{{url('/')}}/<mark></span>
                                        <div class="input-slug">
                                            <input type="text" id="slug" name="slug" value="{{ old('slug', $category->slug) }}" class="form-control @error('slug') is-invalid @enderror" 
                                                onfocusout="convertToSlug($(this))">
                                            @error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputState">{{__('Post::category.parent')}}</label>
                                    <select id="inputState" class="form-control" name="parent_id">
                                        <option value="">None</option>
                                        @foreach ($categories as $cate)
                                            <option value="{{$cate->id}}" {{$cate->id==$category->parent_id? 'selected':''}}>{{ $cate->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                {{-- <div class="form-group">
                                    <div class="form-check">
                                      <input class="form-check-input" {{$category->status==1?'checked':''}} type="checkbox" 
                                        id="gridCheck" name="status" value="1">
                                      <label class="form-check-label" for="gridCheck">Active</label>
                                    </div>
                                </div> --}}
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

modules/post/resources/views/category/index.blade.php
@extends('admin.app')

@section('title', 'SKR | User')
@section('content')
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <span class="lead"><i class="fa fa-list-ul" aria-hidden="true"></i> {{__('Post::category.category_list')}}</span>
                        <a href="{{ route('categories.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>
                            {{__('action.create')}}
                        </a>
                    </div>
                    <div class="card-body ">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>{{__('Post::category.name')}}</th>
                                        <th>{{__('Post::category.slug')}}</th>
                                        <th>{{__('Post::category.parent')}}</th>
                                        <th>{{__('Post::category.active')}}</th>
                                        <th>{{__('layout.action')}}</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmDeleteItem" tabindex="-1" role="dialog" aria-labelledby="modelLabel"
          aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    {{__('action.delete_confirm')}}
                </div>
                <div id="confirmMessage" class="modal-body">
                    {{__('action.delete_sure', ['obj'=>'Category'])}}
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnConfirmDelete" class="btn btn-danger btn-ok"
                            onclick="deleteItem($(this).val())">
                        {{__('action.delete')}}
                    </button>
                    <button type="button" id="confirmCancel" class="btn btn-secondary" data-dismiss="modal"
                            data-toggle="modal" data-target="#confirmDeleteUser">
                        {{__('action.cancel')}}
                    </button>
                </div>
            </div>
        </div>
    </div>
  </section>
</div>
@endsection

@push('page-scripts')
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('categories.index') }}",
        columns: [
            {data: 'name', name: 'name'},
            {data: 'slug', name: 'slug'},
            {data: 'parent', name: 'parent'},
            {data: 'status', name: 'status'}
        ],
        columnDefs: [{
            "targets": 4, 
            "data": null,
            "render": function (data) {
                edit_url = "{{ url('admin/categories') }}/" + data.id + "/edit";
                delete_event = ' onclick = checkItemExisted(' + data.id + ') ';
                return '<a class="btn btn-primary btn-sm" href=' + edit_url + '><span class="fa fa-edit"></span></a> ' +
                '<button class="btn btn-sm btn-danger" ' + delete_event + 'id="row_' + data.id + '" data-toggle="modal" data-target="#confirmDeleteItem" >' +
                '<span class="fa fa-trash" ></span></button> ';
            }
        }],
    });

    function checkItemExisted(id) {
        $('#btnConfirmDelete').val(id);
    }

    function deleteItem(id) {
        let delete_URL = "{{ url('admin/categories') }}/" + id;
        let request = $.ajax({
            url: delete_URL,
            method: "DELETE"
        }).done(function (data){
            $("#confirmDeleteItem").modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
            
            switch (data.status_code) {
                case 500:
                    iziToast.error({
                        title: 'Error',
                        message: data.message,
                        position: 'topRight'
                    });
                    break;
                case 200:
                    $(`#row_${data.row_id}`).closest("tr").remove();
                    iziToast.success({
                        title: 'Success',
                        message: data.message,
                        position: 'topRight',
                    });
                    break;
                default:
                    break;
            }
        });
    }

    function changeStatus(id){
        ajax_URL = "{{ url('admin/categories/status') }}/" + id;
        let request = $.ajax({
            url: ajax_URL,
            method: "POST"
        }).done(function(data) {
            switch (data.status_code) {
                case 500:
                    iziToast.error({
                        title: 'Error',
                        message: data.message,
                        position: 'topRight'
                    });
                    break;
                case 200:
                    iziToast.success({
                        title: 'Success',
                        message: data.message,
                        position: 'topRight',
                    });
                    break;
                default:
                    break;
            }
        });
    }

</script>
@endpush