routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('lang/{lang}', 'LangController@setLanguage')->name('lang');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function (){
    Route::get('/', 'HomeController@getIndex')->name('home');
    Route::get('/dashboard', 'HomeController@getIndex')->name('dashboard');

    //users
    Route::get('/profile', 'UserController@getUserProfile')->name('user.profile.index');
    Route::post('/profile', 'UserController@updateUserProfile')->name('user.profile.update');
    Route::post('/change-password', 'UserController@changePassword')->name('user.profile.change-password');

    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/groups', 'GroupController');
    Route::resource('/menus', 'MenuController');
    Route::resource('/contacts', 'ContactController');
    Route::resource('/pages', 'PageController');

    Route::group(['prefix' => 'services'], function (){
        Route::get('/{slug}', 'ServiceController@index')->name('services.index');
        Route::get('/create/{type}', 'ServiceController@create')->name('services.create');
        Route::post('/store', 'ServiceController@store')->name('services.store');
        Route::get('/edit/{id}', 'ServiceController@edit')->name('services.edit');
        Route::post('/update/{id}', 'ServiceController@update')->name('services.update');
        Route::post('/destroy/{id}', 'ServiceController@destroy')->name('services.destroy');
    });

    Route::get('/about', 'AboutController@index')->name('about.index');
    Route::post('/about', 'AboutController@store')->name('about.store');

    Route::get('/activity-logs', 'ActivityController@getIndex')->name('activity.index');
    Route::post('/activity-logs/clear', 'ActivityController@getClear')->name('activity.clear');

    Route::group(['prefix' => 'setting'], function (){
        Route::get('general', 'SettingController@getGeneral')->name('admin.setting');
        Route::post('email/edit', [
            'as' => 'settings.email.edit',
            'uses' => 'SettingController@postEditEmailConfig',
        ]);
        Route::post('email/test', [
            'as' => 'settings.email.test',
            'uses' => 'SettingController@postTestEmailConfig',
        ]);

        Route::post('general/edit', [
            'as' => 'settings.general.edit',
            'uses' => 'SettingController@postEditGeneral',
        ]);
        Route::group(['prefix' => 'cache'], function () {
            Route::get('', [
                'as'         => 'system.cache',
                'uses'       => 'SettingController@getCacheManagement',
            ]);

            Route::post('clear', [
                'as'         => 'system.cache.clear',
                'uses'       => 'SettingController@postClearCache',

            ]);
        });
    });

});

Route::group(['namespace' => 'Frontend'], function (){
    Route::get('/', 'HomeController@getIndex')->name('frontend.home.index');
    Route::post('/contact-us', 'ContactController@sendContact')->name('frontend.contact.send');

    Route::get('/analytics', function(){
        $analyticsData = Analytics::fetchVisitorsAndPageViews(Spatie\Analytics\Period::days(7));
        dd($analyticsData);
    });

    
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password', 'avatar', 'phone', 'address', 'status', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\Contracts\IUser;
use App\Repositories\Contracts\IRole;
use App\Http\Requests\UserRequest;
use App\Http\Requests\ProfileRequest;
use Illuminate\Support\Facades\Storage;
use Auth;
use Hash;

class UserController extends Controller
{
    protected $userRepository, $roleRepository;

    public function __construct(IUser $userRepository, IRole $roleRepository)
    {
        $this->userRepository = $userRepository;
        $this->roleRepository = $roleRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            return $this->userRepository->datatable();
        }
        return View('admin.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roleRepository->all();
        return view('admin.user.add', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $data = $request->except(['_token']);
        $data['password'] = bcrypt($data['password']);
        if ($request->hasFile('avatar')) {
            $file = $request->file('avatar');
            $data['avatar'] = time().'_'.$file->getClientOriginalName();
            $file->move('uploads/images/avatars/', $data['avatar']);
        }

        $this->userRepository->create($data);
        return redirect()->route('users.index')->with([
            'flash_level'   => 'success',
            'flash_message' => trans('action.add_success', ['obj'=> 'User'])
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userRepository->find($id);
        $roles = $this->roleRepository->all();
        return view('admin.user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        $data = $request->except(['_token']);
        $user = $this->userRepository->find($id);
        
        if ($request->hasFile('avatar')) {
            //remove old file
            if($user->avatar){
                unlink("uploads/images/avatars/".$user->avatar); 
            }
            $file = $request->file('avatar');
            $data['avatar'] = time().'_'.$file->getClientOriginalName();
            $file->move('uploads/images/avatars/', $data['avatar']);
        }

        $this->userRepository->update($id, $data);
        return redirect()->route('users.index')->with([
            'flash_level'   => 'success',
            'flash_message' => trans('action.update_success', ['obj'=> 'User'])
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($this->userRepository->delete($id)){
            return response()->json([
                'row_id' => $id,
                'message' => trans('action.delete_success', ['obj'=> 'User']),
                'status_code' => 200
            ], 200);
        }
        else{
            return response()->json([
                'row_id' => $id,
                'message' => trans('action.has_error'),
                'status_code' => 500
            ], 500);
        }
    }

    public function getUserProfile(){
        $user = Auth::user();
        $roles = $this->roleRepository->all();
        return view('admin.user.profile', compact('user', 'roles'));
    }

    public function updateUserProfile(ProfileRequest $request){
        $data = $request->except(['_token']);

        $user = $this->userRepository->find(Auth::id());
        
        if ($request->hasFile('avatar')) {
            //remove old file
            if ($user->avatar) {
                try {
                    Storage::delete('images/' . $user->avatar);
                } catch (\Exception $e) {
                    return $e->getMessage(); 
                }
            }
            $file = $request->file('avatar');
            $data['avatar'] = time() . '_' . $file->getClientOriginalName();
            Storage::putFileAs('images', $file, $data['avatar']);
        }

        $this->userRepository->update(Auth::id(), $data);
        return redirect()->route('user.profile.index')->with([
            'flash_level'   => 'success',
            'flash_message' => trans('action.update_success', ['obj'=> 'Profile'])
        ]);
    }

    public function changePassword(Request $request){
        $validatedData = $request->validate([
            'old_password' => 'required',
            'new_password' => 'required|min:6',
            'password_confirmation' => 'required|same:new_password',
        ]);

        if (!Hash::check($request->old_password, Auth::user()->password)){
            return redirect()->route('user.profile.index')->with([
                'flash_level'   => 'error',
                'flash_message' => trans('message.incorrect_password')
            ]);
        }
        $this->userRepository->update(Auth::id(), [
            'password' => bcrypt($request->new_password)
        ]);

        return redirect()->route('user.profile.index')->with([
            'flash_level'   => 'success',
            'flash_message' => trans('message.change_passpword_success')
        ]);
    }

}

resources/views/admin/user/add.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('layout.add_user')}}</div>
                        <div class="card-body">
                            <form action="{{route('users.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="name">{{__('layout.name')}}</label>
                                    <input type="text" id="name" name="name" value="{{ old('name') }}" 
                                        class="form-control @error('name') is-invalid @enderror">
                                    @error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="username">{{__('layout.username')}}</label>
                                    <input type="text" id="username" name="username" value="{{ old('username') }}" 
                                        class="form-control @error('username') is-invalid @enderror">
                                    @error('username')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="email">{{__('layout.email')}}</label>
                                    <input type="text" id="email" name="email" value="{{ old('email') }}" 
                                        class="form-control @error('email') is-invalid @enderror">
                                    @error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="password">{{__('layout.password')}}</label>
                                    <input type="password" id="password" name="password" value="{{ old('password') }}" 
                                        class="form-control @error('password') is-invalid @enderror">
                                    @error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="password_confirmation">{{__('layout.password_confirm')}}</label>
                                    <input type="password" id="password_confirmation" name="password_confirmation" 
                                        value="{{ old('password_confirmation') }}" 
                                        class="form-control @error('password_confirmation') is-invalid @enderror">
                                    @error('password_confirmation')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="role_id">{{__('layout.role')}}</label>
                                    <select id="role_id" class="form-control" name="role_id">
                                        <option value="">--Select role--</option>
                                        @foreach($roles as $role)
                                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="avatar">{{__('layout.avatar')}}</label>
                                    <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.choose_file')}}</label>
                                    <input type="file" onchange="readImage(this)" name="avatar" id="upload-photo" class="@error('password_confirmation') is-invalid @enderror" hidden/>
                                    <img id="img-preview" src="" alt="" class="img-thumbnail">
                                    @error('avatar')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> {{__('action.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('layout.add_user')}}</div>
                        <div class="card-body">
                            <form action="{{ route('users.update', $user->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="name">{{__('layout.name')}}</label>
                                    <input type="text" id="name" name="name" value="{{ old('name', $user->name) }}" 
                                        class="form-control @error('name') is-invalid @enderror">
                                    @error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="username">{{__('layout.username')}}</label>
                                    <input type="text" id="username" name="username" value="{{ old('username', $user->username) }}" 
                                        class="form-control @error('username') is-invalid @enderror">
                                    @error('username')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="email">{{__('layout.email')}}</label>
                                    <input type="text" id="email" name="email" value="{{ old('email', $user->email) }}" 
                                        class="form-control @error('email') is-invalid @enderror">
                                    @error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="role_id">{{__('layout.role')}}</label>
                                    <select id="role_id" class="form-control" name="role_id">
                                        <option value="">--Select role--</option>
                                        @foreach($roles as $role)
                                        <option value="{{ $role->id }}" {{$role->id==$user->role_id? 'selected':''}}>{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="avatar">{{__('layout.avatar')}}</label>
                                    <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.choose_file')}}</label>
                                    <input type="file" onchange="readImage(this)" name="avatar" id="upload-photo" hidden/>
                                    <img id="img-preview" src="{{ asset("uploads/images/avatars/$user->avatar") }}" alt="" class="img-thumbnail">
                                    @error('avatar')<div class="text-danger">{{ $message }}</div>@enderror
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> {{__('action.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.app')

@section('title', 'SKR | User')
@section('content')
<div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <span class="lead"><i class="fa fa-list-ul" aria-hidden="true"></i> {{__('layout.user_list')}}</span>
                        <a href="{{ route('users.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>
                            {{__('action.create')}}
                        </a>
                    </div>
                    <div class="card-body ">
                        <div class="table-responsive">
                            <table id="dataTable" class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>{{__('layout.name')}}</th>
                                        <th>{{__('layout.username')}}</th>
                                        <th>{{__('layout.email')}}</th>
                                        <th>{{__('layout.action')}}</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="confirmDeleteItem" tabindex="-1" role="dialog" aria-labelledby="modelLabel"
          aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    {{__('action.delete_confirm')}}
                </div>
                <div id="confirmMessage" class="modal-body">
                    {{__('action.delete_sure', ['obj'=>'user'])}}
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnConfirmDelete" class="btn btn-danger btn-ok"
                            onclick="deleteItem($(this).val())">
                        {{__('action.delete')}}
                    </button>
                    <button type="button" id="confirmCancel" class="btn btn-secondary" data-dismiss="modal"
                            data-toggle="modal" data-target="#confirmDeleteUser">
                        {{__('action.cancel')}}
                    </button>
                </div>
            </div>
        </div>
    </div>
  </section>
</div>
@endsection

@push('page-scripts')
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('users.index') }}",
        columns: [
            { data: 'name', name: 'name' },
            { data: 'username', name: 'username' },
            { data: 'email', name: 'email' }
        ],
        columnDefs: [{
            "targets": 3, 
            "data": null,
            "render": function (data) {
                edit_url = "{{ url('admin/users') }}/" + data.id + "/edit";
                delete_event = ' onclick = checkItemExisted(' + data.id + ') ';
                return '<a class="btn btn-primary btn-sm" href=' + edit_url + '><span class="fa fa-edit"></span></a> ' +
                '<button class="btn btn-sm btn-danger" ' + delete_event + 'id="row_' + data.id + '" data-toggle="modal" data-target="#confirmDeleteItem" >' +
                '<span class="fa fa-trash" ></span></button> ';
            }
        }],
    });

    function checkItemExisted(id) {
        $('#btnConfirmDelete').val(id);
    }

    function deleteItem(id) {
        let delete_URL = "{{ url('admin/users') }}/" + id;
        let request = $.ajax({
            url: delete_URL,
            method: "DELETE"
        }).done(function (data) {
            $("#confirmDeleteItem").modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
            
            if(data.status_code == 500){
                iziToast.success({
                    title: 'Error',
                    message: data.message,
                    position: 'topRight'
                });
            }
            else {
                $(`#row_${data.row_id}`).closest("tr").remove();
                iziToast.success({
                    title: 'Message',
                    message: data.message,
                    position: 'topRight'
                });
            }
        });
    }
</script>
@endpush

resources/views/admin/user/profile.blade.php
@extends('admin.app')

@section('title', 'SKR | Users')

@section('content')
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary card-outline">
                        <div class="card-header"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{__('layout.user_profile')}}</div>
                        <div class="card-body">
                            <form action="{{route('user.profile.index')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="name">{{__('layout.name')}}</label>
                                    <input type="text" id="name" name="name" value="{{ old('name', $user->name) }}" 
                                        class="form-control @error('name') is-invalid @enderror">
                                    @error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="username">{{__('layout.username')}}</label>
                                    <input type="text" id="username" name="username" value="{{ old('username', $user->username) }}" 
                                        class="form-control @error('username') is-invalid @enderror">
                                    @error('username')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="email">{{__('layout.email')}}</label>
                                    <input type="text" id="email" name="email" value="{{ old('email', $user->email) }}" 
                                        class="form-control @error('email') is-invalid @enderror">
                                    @error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="role_id">{{__('layout.role')}}</label>
                                    <select id="role_id" class="form-control" name="role_id">
                                        <option value="">--Select role--</option>
                                        @foreach($roles as $role)
                                        <option value="{{ $role->id }}" {{$user->role_id == $role->id? 'selected': ''}}>{{ $role->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="avatar">{{__('layout.avatar')}}</label>
                                    <label class="upload-photo btn btn-success btn-sm" for="upload-photo">{{__('action.choose_file')}}</label>
                                    <input type="file" onchange="readImage(this)" name="avatar" id="upload-photo" class="@error('password_confirmation') is-invalid @enderror" hidden/>
                                    <img id="img-preview" src="{{ asset("storage/images/$user->avatar") }}" alt="" class="img-thumbnail">
                                    @error('avatar')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> {{__('action.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-right">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <i class="fa fa-unlock-alt" aria-hidden="true"></i> {{__('layout.change_password')}}
                        </div>
                        <div class="card-body">
                            <form action="{{route('user.profile.change-password')}}" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label>{{__('layout.old_password')}}</label>
                                    <input type="password" name="old_password" value="{{ old('old_password') }}" placeholder="{{__('layout.old_password')}}"
                                        class="form-control @error('old_password') is-invalid @enderror">
                                    @error('old_password')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="password">{{__('layout.new_password')}}</label>
                                    <input type="password" id="password" name="new_password" value="{{ old('new_password') }}" placeholder="{{__('layout.new_password')}}"
                                        class="form-control @error('new_password') is-invalid @enderror">
                                    @error('new_password')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <div class="form-group">
                                    <label for="password_confirmation">{{__('layout.password_confirm')}}</label>
                                    <input type="password" id="password_confirmation" name="password_confirmation" 
                                        value="{{ old('password_confirmation') }}" placeholder="{{__('layout.password_confirm')}}"
                                        class="form-control @error('password_confirmation') is-invalid @enderror">
                                    @error('password_confirmation')<div class="invalid-feedback">{{ $message }}</div>@enderror
                                </div>
                                <hr>
                                <div class="text-right">
                                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-save"></i> Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection